//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sth1edwv.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sth1edwv.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die $15580 Green Hill Act 1
        ///$15582 Green Hill Act 2
        ///$15584 Green Hill Act 3
        ///$15586 Bridge Act 1
        ///$15588 Bridge Act 2
        ///$1558A Bridge Act 3
        ///$1558C Jungle Act 1
        ///$1558E Jungle Act 2
        ///$15590 Jungle Act 3
        ///$15592 Labyrinth Act 1
        ///$15594 Labyrinth Act 2
        ///$15596 Labyrinth Act 3
        ///$15598 Scrap Brain Act 1
        ///$1559A Scrap Brain Act 2
        ///$1559C Scrap Brain Act 3
        ///$1559E Sky Base Act 1
        ///$155A0 Sky Base Act 2
        ///$155A2 Sky Base Act 3
        ///$155A4 End Sequence
        ///$155A8 Scrap Brain Act 2 (Emerald Maze), from corridor
        ///$155AA Scrap Br [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string levels {
            get {
                return ResourceManager.GetString("levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die $00000 Main Game Code
        ///$0024B Labyrinth Act 1-2 Underwater Palette
        ///$0026B Labyrinth Act 3 Underwater Palette
        ///$00F0E Map Screen 1 Palette
        ///$00F2E Map Screen 2 Palette
        ///$01209 Zone Title Pointers:
        ///$01209 Green Hill Act 1 (=$122D)
        ///$0120B Green Hill Act 2 (=$122D)
        ///$0120D Green Hill Act 3 (=$122D)
        ///$0120F Bridge Act 1 (=$123C)
        ///$01211 Bridge Act 2 (=$123C)
        ///$01213 Bridge Act 3 (=$123C)
        ///$01215 Jungle Act 1 (=$124B)
        ///$01217 Jungle Act 2 (=$124B)
        ///$01219 Jungle Act 3 (=$124B)
        ///$0121B Labyrinth Act 1 (=$125A)        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
    }
}
